CREATE TABLE IF NOT EXISTS Device (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    battery_power INT,
    blue INT,
    clock_speed FLOAT,
    dual_sim INT,
    fc INT,
    four_g FLOAT,
    int_memory INT,
    m_dep FLOAT,
    mobile_wt INT,
    n_cores INT,
    PC INT,
    px_height INT,
    px_width INT,
    ram INT,
    sc_h INT,
    sc_w INT,
    talk_time INT,
    three_g INT,
    touch_screen INT,
    wifi INT,
    price_range INT
);